import { Numeric } from "./maths/numeric";
import { NumExp } from "./maths/expressions/numexp";
import { Shutingyard } from "./maths/shutingyard";
import { Random } from "./maths/randomization/random";
import { Fraction } from "./maths/coefficients/fraction";
import { Nthroot } from "./maths/coefficients/nthroot";
import { Monom } from "./maths/algebra/monom";
import { Polynom } from "./maths/algebra/polynom";
import { Equation } from "./maths/algebra/equation";
import { LinearSystem } from "./maths/algebra/linearSystem";
import { Rational } from "./maths/algebra/rational";
import { Logicalset } from "./maths/algebra/logicalset";
import { PolynomExpFactor, PolynomExpProduct } from "./maths/expressions/polynomexp";
import { Vector } from "./maths/geometry/vector";
import { Line } from "./maths/geometry/line";
import { Triangle } from "./maths/geometry/triangle";
import { Circle } from "./maths/geometry/circle";
import { Point } from "./maths/geometry/point";
export declare const PiMath: {
    ShutingYard: typeof Shutingyard;
    Numeric: typeof Numeric;
    NumExp: typeof NumExp;
    Fraction: typeof Fraction;
    Root: typeof Nthroot;
    Monom: typeof Monom;
    Polynom: typeof Polynom;
    Equation: typeof Equation;
    LinearSystem: typeof LinearSystem;
    Rational: typeof Rational;
    Logicalset: typeof Logicalset;
    Random: typeof Random;
    PolynomExpFactor: typeof PolynomExpFactor;
    PolynomExpProduct: typeof PolynomExpProduct;
    Geometry: {
        Vector: typeof Vector;
        Point: typeof Point;
        Line: typeof Line;
        Triangle: typeof Triangle;
        Circle: typeof Circle;
    };
};
