import { Numeric } from "./maths/numeric";
import { NumExp } from "./maths/expressions/numexp";
import { Shutingyard } from "./maths/shutingyard";
import { Random } from "./maths/randomization/random";
import { Fraction, Nthroot } from "./maths/coefficients";
import { Monom, Polynom, Equation, LinearSystem, Rational, Logicalset, PolynomExpFactor, PolynomExpProduct } from "./maths/algebra";
import { Line, Circle, Triangle, Point, Vector } from "./maths/geometry";
export declare const Pi: {
    ShutingYard: typeof Shutingyard;
    Numeric: typeof Numeric;
    NumExp: typeof NumExp;
    Fraction: typeof Fraction;
    Root: typeof Nthroot;
    Monom: typeof Monom;
    Polynom: typeof Polynom;
    Equation: typeof Equation;
    LinearSystem: typeof LinearSystem;
    Rational: typeof Rational;
    Logicalset: typeof Logicalset;
    Random: typeof Random;
    PolynomExpFactor: typeof PolynomExpFactor;
    PolynomExpProduct: typeof PolynomExpProduct;
    Geometry: {
        Vector: typeof Vector;
        Point: typeof Point;
        Line: typeof Line;
        Triangle: typeof Triangle;
        Circle: typeof Circle;
    };
};
