import type { IAlgebra, IAnalyse, IExpression, InputAlgebra, InputValue, IPiMathObject, ISolution, literalType, TABLE_OF_SIGNS } from "../pimath.interface";
import { Fraction } from "../coefficients";
import { Monom } from './monom';
export type PolynomParsingType = InputValue<Polynom> | Monom;
export interface IEuclidean {
    quotient: Polynom;
    reminder: Polynom;
}
export declare class Polynom implements IPiMathObject<Polynom>, IExpression<Polynom>, IAnalyse<Polynom>, IAlgebra<Polynom> {
    #private;
    constructor(value: InputValue<Fraction>);
    constructor(value: string);
    constructor(value: Monom);
    constructor(value: Polynom);
    constructor(...values: InputValue<Fraction>[]);
    constructor(...values: InputAlgebra<Polynom>[]);
    parse: (inputStr: PolynomParsingType, ...values: InputAlgebra<Monom>[]) => this;
    clone: () => Polynom;
    get tex(): string;
    get display(): string;
    get value(): number | undefined;
    add: (...values: InputAlgebra<Polynom>[]) => Polynom;
    commonMonom: () => Monom;
    degree: (letter?: string) => Fraction;
    derivative: (letter?: string) => Polynom;
    divide: (value: InputAlgebra<Polynom>) => Polynom;
    empty: () => this;
    euclidean: (P: Polynom) => IEuclidean;
    evaluate: (values: literalType<Fraction | number> | InputValue<Fraction>, asNumeric?: boolean) => Fraction | number;
    factorize: (letter?: string) => Polynom[];
    fromCoefficients(...values: InputValue<Fraction>[]): this;
    gcdDenominator: () => number;
    gcdNumerator: () => number;
    getCoefficients(): Fraction[];
    getDenominators: () => number[];
    getNumerators: () => number[];
    getZeroes: () => ISolution[];
    hasVariable(letter: string): boolean;
    integrate: (a: InputValue<Fraction>, b: InputValue<Fraction>, letter?: string) => Fraction;
    inverse(): Polynom | undefined;
    isDeveloped: (polynomString: string) => boolean;
    isDividableBy: (div: Polynom) => boolean;
    isEqual: (P: Polynom) => boolean;
    get isMultiVariable(): boolean;
    isOne(): boolean;
    isOppositeAt: (P: Polynom) => boolean;
    isReduced: (polynomString: string) => boolean;
    isSameAs: (P: Polynom) => boolean;
    isZero(): boolean;
    lcmDenominator: () => number;
    lcmNumerator: () => number;
    get length(): number;
    letters: () => string[];
    limitToInfinity: (letter?: string) => Fraction;
    limitToNegativeInfinity: (letter?: string) => Fraction;
    monomByDegree: (degree?: Fraction | number, letter?: string) => Monom;
    monomByLetter: (letter: string) => Monom;
    get monoms(): Monom[];
    set monoms(M: Monom[]);
    monomsByDegree: (degree?: number | Fraction, letter?: string) => Monom[];
    multiply: (value: unknown) => Polynom;
    get numberOfVars(): number;
    one: () => this;
    opposite: () => this;
    get plotFunction(): string;
    pow: (nb: number) => Polynom;
    primitive: (letter?: string) => Polynom;
    reduce: () => Polynom;
    reorder: (letter?: string, revert?: boolean) => this;
    replaceBy: (letter: string, P: Polynom) => this;
    root(): Polynom;
    get roots(): ISolution[];
    set roots(value: ISolution[]);
    sqrt(): Polynom;
    subtract: (...values: InputAlgebra<Polynom>[]) => Polynom;
    tableOfSigns(): TABLE_OF_SIGNS;
    get variables(): string[];
    zero: () => this;
    get zeroes(): ISolution[];
}
//# sourceMappingURL=polynom.d.ts.map