import type { IAlgebra, IAnalyse, IExpression, InputAlgebra, InputValue, IPiMathObject, literalType, TABLE_OF_SIGNS } from "../pimath.interface";
import { Fraction } from "../coefficients";
import { Monom } from './monom';
import { Solution } from "../analyze/solution";
export type PolynomParsingType = InputValue<Polynom> | Monom;
export interface IEuclidean {
    quotient: Polynom;
    reminder: Polynom;
}
export declare class Polynom implements IPiMathObject<Polynom>, IExpression<Polynom>, IAnalyse<Polynom>, IAlgebra<Polynom> {
    #private;
    constructor(value: InputValue<Fraction>);
    constructor(value: string);
    constructor(value: Monom);
    constructor(value: Polynom);
    constructor(...values: InputValue<Fraction>[]);
    constructor(...values: InputAlgebra<Polynom>[]);
    parse(inputStr: PolynomParsingType, ...values: InputAlgebra<Monom>[]): this;
    clone(): Polynom;
    get tex(): string;
    get display(): string;
    static xMultiply(...polynoms: InputValue<Polynom>[]): Polynom;
    add(...values: InputAlgebra<Polynom>[]): this;
    commonMonom(): Monom;
    degree(letter?: string): Fraction;
    derivative(letter?: string): Polynom;
    divide(value: InputAlgebra<Polynom>): this;
    empty(): this;
    euclidean(P: Polynom): IEuclidean;
    evaluate(values: literalType<Fraction | number> | InputValue<Fraction>, asNumeric: true): number;
    evaluate(values: literalType<Fraction | number> | InputValue<Fraction>, asNumeric?: false): Fraction;
    evaluate(values: literalType<Fraction | number> | InputValue<Fraction>, asNumeric?: boolean): Fraction | number;
    factorize(_letter?: string): Polynom[];
    get factors(): Polynom[];
    fromCoefficients(...values: InputValue<Fraction>[]): this;
    gcdDenominator(): number;
    gcdNumerator(): number;
    getCoefficients(): Fraction[];
    getDenominators(): number[];
    getNumerators(): number[];
    getZeroes(): Solution[];
    hasVariable(letter: string): boolean;
    integrate(a: InputValue<Fraction>, b: InputValue<Fraction>, letter?: string): Fraction;
    inverse(): Polynom | undefined;
    isDeveloped(polynomString: string): boolean;
    isDividableBy(div: Polynom): boolean;
    isEqual(P: Polynom): boolean;
    get isMultiVariable(): boolean;
    isOne(): boolean;
    isOppositeAt(P: Polynom): boolean;
    isSameAs(P: Polynom): boolean;
    isZero(): boolean;
    lcmDenominator(): number;
    lcmNumerator(): number;
    get length(): number;
    limitTo(value: InputValue<Fraction>, letter?: string): Fraction;
    monomByDegree(degree?: Fraction | number, letter?: string): Monom;
    monomByLetter(letter: string): Monom;
    get monoms(): Monom[];
    set monoms(M: Monom[]);
    monomsByDegree(degree?: number | Fraction, letter?: string): Monom[];
    multiply(value: InputAlgebra<Polynom>): this;
    get numberOfVars(): number;
    one(): this;
    opposite(): this;
    get plotFunction(): string;
    pow(nb: number): Polynom;
    primitive(letter?: string): Polynom;
    reduce(): this;
    reorder(letter?: string, revert?: boolean): this;
    replaceBy(letter: string, P: Polynom): this;
    root(): Polynom;
    get roots(): Solution[];
    set roots(value: Solution[]);
    setVariable(value: string): this;
    sqrt(): Polynom;
    subtract(...values: InputAlgebra<Polynom>[]): this;
    tableOfSigns(): TABLE_OF_SIGNS;
    get value(): number | undefined;
    get variables(): string[];
    zero(): this;
    get zeroes(): Solution[];
}
//# sourceMappingURL=polynom.d.ts.map