import Fraction from "../coefficients/fraction";
export default class Vector {
    private _x;
    private _y;
    constructor(...values: any);
    get isVector(): boolean;
    get x(): Fraction;
    set x(value: Fraction);
    get y(): Fraction;
    set y(value: Fraction);
    get normSquare(): Fraction;
    get norm(): number;
    get tex(): string;
    parse: (...values: any) => Vector;
    clone: () => Vector;
    reset: () => Vector;
    zero: () => Vector;
    one: () => Vector;
    private _parseString;
    opposed: () => Vector;
    add: (V: Vector) => Vector;
    subtract: (V: Vector) => Vector;
    scalarProductWithVector: (V: Vector) => Fraction;
    static scalarProduct: (v1: Vector, v2: Vector) => number;
    normal: () => Vector;
    isNormalTo: (v: Vector) => boolean;
    multiplyByScalar: (k: any) => Vector;
    divideByScalar: (k: any) => Vector;
    simplify: () => Vector;
    angleWith: (V: Vector, sharp?: Boolean, radian?: Boolean) => number;
}
