import { InputValue, IPiMathObject } from '../pimath.interface';
import { Fraction } from '../coefficients';
import { TupleN } from './TupleN';
import { Point } from './point';
export declare class Vector extends TupleN implements IPiMathObject<Vector> {
    constructor(...values: (Vector | Point)[] | InputValue<Fraction>[]);
    parse(...values: (Vector | Point)[] | InputValue<Fraction>[]): this;
    clone(): Vector;
    get tex(): string;
    get display(): string;
    static asDisplay(...values: string[]): string;
    static asTex(...values: string[]): string;
    add: (V: Vector) => this;
    angle: (V: Vector, sharp?: boolean, radian?: boolean) => number;
    cross(value: Vector): Vector;
    divideByScalar: (k: InputValue<Fraction>) => this;
    dot: (V: Vector | Point) => Fraction;
    fromString(value: string): this;
    isColinearTo: (v: Vector) => boolean;
    isEqual: (v: Vector) => boolean;
    isNormalTo: (v: Vector) => boolean;
    get isNull(): boolean;
    isOne(): boolean;
    isZero(): boolean;
    multiplyByScalar: (k: InputValue<Fraction>) => this;
    get norm(): number;
    get normSquare(): Fraction;
    normal: () => this;
    one: () => this;
    opposite: () => this;
    simplify: () => this;
    subtract: (V: Vector) => this;
    translate(...values: Fraction[]): this;
    unit: () => this;
}
