export declare class Fraction {
    private _numerator;
    private _denominator;
    constructor(value?: any, denominatorOrPeriodic?: number);
    get isFraction(): boolean;
    get numerator(): number;
    set numerator(value: number);
    get denominator(): number;
    set denominator(value: number);
    get value(): number;
    get tex(): string;
    get display(): string;
    get frac(): string;
    get dfrac(): string;
    parse: (value: any, denominatorOrPeriodic?: number) => Fraction;
    clone: () => Fraction;
    zero: () => Fraction;
    one: () => Fraction;
    infinite: () => Fraction;
    invalid: () => Fraction;
    opposed: () => Fraction;
    add: (F: Fraction) => Fraction;
    subtract: (F: Fraction) => Fraction;
    multiply: (F: Fraction | number) => Fraction;
    divide: (F: Fraction | number) => Fraction;
    invert: () => Fraction;
    pow: (p: number) => Fraction;
    root: (p: number) => Fraction;
    sqrt: () => Fraction;
    abs: () => Fraction;
    reduce: () => Fraction;
    amplify: (k: number) => Fraction;
    compare: (F: Fraction, sign?: string) => boolean;
    lesser: (than: Fraction) => Boolean;
    leq: (than: Fraction) => Boolean;
    greater: (than: Fraction) => Boolean;
    geq: (than: Fraction) => Boolean;
    isEqual: (than: Fraction) => boolean;
    isDifferent: (than: Fraction) => boolean;
    isOpposed: (p: Fraction) => boolean;
    isInverted: (p: Fraction) => boolean;
    isZero: () => boolean;
    isOne: () => boolean;
    isPositive: () => boolean;
    isNegative: () => boolean;
    isNaN: () => boolean;
    isInfinity: () => boolean;
    isFinite: () => boolean;
    isSquare: () => boolean;
    isReduced: () => boolean;
    sign: () => number;
    areEquals: (...F: Fraction[]) => boolean;
}
